version: "3.7"
services:
  rlcraft:
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - "25565:25565"
    environment:
      VERSION: 1.12.2
      EULA: "TRUE"
      TYPE: "FORGE"
      FORGEVERSION: 14.23.5.2860
      MEMORY: "7G"
      GENERIC_PACK: https://mediafilez.forgecdn.net/files/2935/323/RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip
      GENERIC_PACK_STRIP_DIRS: "0"
    volumes:
      - ./data:/data
